### PR TITLE
Adding class attributes to both links and action fields.

### PR DESCRIPTION
**Pull request by kevinswiber**
Links and action fields are the only elements left without optional class values.  This corrects that.

### CODE REVIEW

**Comment by mdobson** [comment]
Interesting. Would this be a proper application of `class` on a link per the example?

```json
  "links": [
    { "class":["order"], "rel": [ "self" ], "href": "http://api.x.io/orders/42" },
    { "class":["order"], "rel": [ "previous" ], "href": "http://api.x.io/orders/41" },
    { "class":["order"], "rel": [ "next" ], "href": "http://api.x.io/orders/43" }
  ]
```

**Comment by kevinswiber** [comment]
@mdobson Yes.  Or something like:

```json
  "links": [
    { "class":["completed"], "rel": [ "self" ], "href": "http://api.x.io/orders/42" },
    { "class":["cancelled"], "rel": [ "previous" ], "href": "http://api.x.io/orders/41" },
    { "class":["processing"], "rel": [ "next" ], "href": "http://api.x.io/orders/43" }
  ]
```

The goal is for Siren to offer the capability to provide semantic identifiers that can be applied to the element for client processing.

**Comment by ericelliott** [comment]
:+1:

**Comment by ryanhiebert** [comment]
This seems really strange to me. The `class` seems like it should be a property of the related resource, not of the link itself. I think what I'd prefer to see is the link relations in a separate layer of abstraction from the `href` and `rel`. For example:

```json
"links": [
  { "rel": [ "self" ], "href": "http://api.x.io/orders/42",
    "entity": { "class": ["completed"] }
  },
  { "rel": [ "self" ], "href": "http://api.x.io/orders/41",
    "entity": { "class": ["cancelled"] }
  },
  { "rel": [ "self" ], "href": "http://api.x.io/orders/43",
    "entity": { "class": ["processing"] }
  }
]
```

You might also guess from my example that I also think that it makes sense to allow partial representations in links.


The main issue I have with this is that the `class` seems to me like a property of the resource, while `rel` and `href` seem like part of the hypermedia metadata. I think that both are incredibly powerful and important, I'm just not convinced that the `class` is important for the hypermedia part of things. Perhaps I just need a different perspective on the motivation of `class` to understand it properly.

**Comment by kevinswiber** [comment]
@ryanhiebert The class is intended to offer domain semantics to elements of the current representation.  It's not a partial.  I would argue if you need partials, you should be looking at sub-entities.

Think about the use case of having several potential authors in a representation.  Links could look like so:

```json
 "links": [
    { "rel": [ "self" ], "href": "..." },
    { "class":["primary"], "rel": [ "author" ], "href": "..." },
    { "rel": [ "author" ], "href": "..." }
  ]
```

I think this better illustrates the importance of context.

**Comment by ryanhiebert** [comment]
@kevinswiber I wonder if I'm just finding too much overlap between `rel` and `class`, then. My first thought for those links would be custom link rels with application-defined semantics. Is your idea with `rel` that they should only be well-known types, and application-specific semantics should be in `class`? There must be something important that I'm missing, I'm just not quite sure what it is.

**Comment by kevinswiber** [comment]
The link relation should inform the client _why_ it might want to follow that link.  Class values will inform the client of the link's _characteristics_ in the current context.

Relation: This is a related _author_.
Class:  This is the _primary_ author link.

```json
{ "class":["primary"], "rel": [ "author" ], "href": "..." }
```

In some cases, the class assigned to the link might be repeated on the representation received by following that link.  In some cases, it won't.

It's all about the current context.  

FYI: This is coming up as I'm attempting to map ALPS to Siren:  http://kevinswiber.github.io/siren-alps-mapping/.  I'd like to use class values for attaching semantics, much like in microformats: http://microformats.org/wiki/hlisting.

**Comment by ryanhiebert** [comment]
I've read through the draft of the ALPS mapping, and I'm still not quite getting it. It might be helpful to give an example of a problem you cannot solve now, and would be able to with this change.

In particular, I'm not getting the semantic difference that makes this subtly wrong:

```json
{ "rel": [ "author", "primary" ], "href": "..." }
```

And feel free to tell me to take my confusion to the ML.

**Comment by mdobson** [comment]
Hey Ryan,

The way you have it isn't fundamentally wrong at all. Personally for me I
like this change for a few reasons.

   1. class is prominently used throughout the spec, and having this
   consistency in this particular API entity makes sense
   2. Being able to examine something like class in the response would make
   some consumption scenarios easier. I'd be able to follow a like with a
   specific relation, for a specific class of entity.

Overall I think it offers a separation of context for linking that wouldn't
have previously been there. The old way definitely works, but the new way
would make certain client cases easier.

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Comment by ryanhiebert** [comment]
OK, I'm also thinking about how this affects my understanding of other parts of the spec.

If I want my link to include a partial representation, then it should be moved to _entities_, which allows that. However, what if, as suggested, the `class` for the link is not the same as the class for the entity? AFAICT, there's no way to have a set of classes that apply to the _link_ my entity represents, and other classes that apply to the embedded entity itself.

That implies to me one of three things:

1. We've gotten the idea of a class wrong, and it should only be allowed on the entity.
2. That `entities` is not suitable for links with embedded (partial) representations. It serves a different purpose.
3. That `entities` merges the concepts of links and embedded representations too closely together.

I've been thinking that it was the first, but that doesn't mesh with the conversation we've had here so far. It's also possible that I've missed another interpretation. :smile:

**Comment by kevinswiber** [comment]
@ryanhiebert 

Of your 3 potential implications, none of them apply to this pull request.  That would be an acceptable discussion for the mailing list.

Would you ever use a `class` attribute on an `a` element in HTML?  If you answered "yes," then I'm not sure how you could disagree with this change.

**Comment by ryanhiebert** [comment]
@kevinswiber thanks for talking with me. I'll give it some more thought before bringing it up on the mailing list. It's clear that this thread is now more about my misunderstandings than the pull request. I'm sorry for that.

**Comment by kevinswiber** [comment]
No problem!

**Pull request merged**
