### PR TITLE
adding a title attribute to embedded links

### LINKED ISSUE #55: Add optional title for Embedded Links
All the other types include a `title` attribute, but curiously Embedded Links have this attribute absent.

### PR DESCRIPTION
**Pull request by dominicbarnes**
fixes #55

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Whoops, just noticed that my editor automatically trimmed some whitespace and cluttered up this change request. I'll fix that right away.

**Comment by kevinswiber** [comment]
Cool.  Thank you.

I think you're missing a #.  I think it's 5-deep, #####.

**Comment by dominicbarnes** [comment]
Ah bummer, haha I'll take care of it once I'm back at my desk in about an
hour.

**Comment by dominicbarnes** [comment]
@kevinswiber fixed! :D

**Comment by dominicbarnes** [comment]
Thanks @kevinswiber! I'll be updating my little node library shortly. :)

**Pull request merged**
